### ISSUE TITLE
Rending error

### ISSUE THREAD

**Issue by Hannah-hh** [peteanderson80/Matterport3DSimulator#51]
I reproduced a code that used the Matterport3DSimulator. I have downloaded the dataset and placed it in the appropriate folder as specified. But it still has the following error. I don't know how to solve this problem. Could anyone know how to fix it?

tests is a Catch v2.0.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
RGB Image
-------------------------------------------------------------------------------
/home/cjh/code/regretful-agent/src/test/main.cpp:302
...............................................................................

/home/cjh/code/regretful-agent/src/test/main.cpp:324: FAILED:
  REQUIRE_NOTHROW( sim.newEpisode(scanId, viewpointId, heading, elevation) )
due to unexpected exception with message:
  MatterSim: Could not open skybox files at: ./data/v1/scans/17DRP5sb8fy/
  matterport_skybox_images/85c23efeaecd4d43a7dcd5b90137179e_skybox*_sami.jpg

===============================================================================
test cases:      5 |      4 passed | 1 failed
assertions: 118337 | 118336 passed | 1 failed

**Comment by peteanderson80** [comment]
This looks like code from the repo for the regretful agent paper. I'm afraid I wouldn't know how to support that code because I'm not familiar with it. 

One thing that might help though - the simulator has been updated over time and the install instructions have changed a bit, so there is now a preprocessing step required. It's fully described in the readme. If that doesn't help, I suggest asking the authors of this repo to link to a specific commit that they used in their experiments.

**Comment by Hannah-hh** [comment]
Sorry for not thanking you in time for your answer. Thank you so much. Your answer was very helpful to me.

**Comment by PygmalionChen** [comment]
Have you solve this problem yet? @Hannah-hh
