### ISSUE TITLE
R2R_test.json 'path' error

### ISSUE THREAD

**Issue by xyez** [peteanderson80/Matterport3DSimulator#57]
I downloaded the R2R_test.json file, but found that there's only one viewpoint in the 'path' item. I saw there are several viewpoints in the other files like R2R_train.json. Can you fix the issue?

**Comment by peteanderson80** [comment]
Yes, this is because the aim is to train a model / agent that can predict the full path from the starting point and the instruction. We keep the test paths private to ensure fair evaluations. So the test paths can only be accessed by submitting model predictions to the test server and getting scores.
